"""
Task 6: SQL Security / Hardening Parser.

validate_sql() intercepts every LLM-generated SQL statement and enforces:
  1. SELECT-only — no DDL or DML mutations
  2. Allowed tables only — placements, internships, companies
  3. Correct org_id filter — must be present and must match the request org
  4. No injection patterns — OR 1=1, UNION, comment sequences

Call this BEFORE executing any SQL produced by the NL2SQL agent.
"""
import re
import logging
from typing import Set

logger = logging.getLogger(__name__)

# Tables the agent is allowed to query
_ALLOWED_TABLES: Set[str] = {"placements", "internships", "companies"}

# SQL verbs that mutate state — all forbidden
_FORBIDDEN_VERBS = re.compile(
    r'^\s*(INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|TRUNCATE|REPLACE|MERGE|EXEC|EXECUTE)\b',
    re.IGNORECASE,
)

# Classic injection patterns
_INJECTION_PATTERNS = [
    re.compile(r'\bOR\s+1\s*=\s*1\b', re.IGNORECASE),          # OR 1=1
    re.compile(r'\bOR\s+[\'"]?\w+[\'"]?\s*=\s*[\'"]?\w+[\'"]?\b.*--', re.IGNORECASE),  # OR x=x --
    re.compile(r'--\s', re.IGNORECASE),                          # SQL comment
    re.compile(r'/\*.*?\*/', re.DOTALL),                         # block comment
    re.compile(r'\bUNION\b', re.IGNORECASE),                     # UNION-based injection
    re.compile(r';\s*\w', re.IGNORECASE),                        # stacked queries
]


class SQLSecurityError(Exception):
    """Raised when generated SQL violates a security constraint."""
    pass


def _check_not_empty(sql: str) -> None:
    if not sql or not sql.strip():
        raise SQLSecurityError("Empty SQL statement rejected.")


def _check_select_only(sql: str) -> None:
    m = _FORBIDDEN_VERBS.search(sql)
    if m:
        verb = m.group(1).upper()
        raise SQLSecurityError(
            f"Forbidden SQL verb '{verb}' detected. Only SELECT statements are allowed."
        )
    if not re.match(r'^\s*SELECT\b', sql, re.IGNORECASE):
        raise SQLSecurityError(
            "SQL does not start with SELECT. Only SELECT statements are allowed."
        )


def _check_allowed_tables(sql: str) -> None:
    # Extract all identifiers that follow FROM or JOIN
    referenced = set(re.findall(
        r'(?:FROM|JOIN)\s+([a-zA-Z_][a-zA-Z0-9_]*)',
        sql, re.IGNORECASE
    ))
    disallowed = referenced - _ALLOWED_TABLES
    if disallowed:
        raise SQLSecurityError(
            f"Query references disallowed table(s): {disallowed}. "
            f"Only {_ALLOWED_TABLES} are permitted."
        )


def _check_org_id_present(sql: str, org_id: int) -> None:
    # Must contain org_id = <exact org_id value>
    pattern = re.compile(
        rf'\borg_id\s*=\s*{re.escape(str(org_id))}\b',
        re.IGNORECASE
    )
    if not pattern.search(sql):
        raise SQLSecurityError(
            f"SQL missing required tenant filter: org_id = {org_id}. "
            "All queries must be scoped to a single organization."
        )


def _check_no_injection(sql: str) -> None:
    for pattern in _INJECTION_PATTERNS:
        if pattern.search(sql):
            raise SQLSecurityError(
                f"Potential SQL injection pattern detected: {pattern.pattern!r}"
            )


def validate_sql(sql: str, org_id: int) -> str:
    """
    Validate LLM-generated SQL before execution.

    Checks (in order):
      1. Not empty
      2. SELECT-only (no INSERT/UPDATE/DELETE/DROP/...)
      3. Only allowed tables (placements, internships, companies)
      4. org_id = <org_id> filter present and correct
      5. No injection patterns (OR 1=1, UNION, comments, stacked queries)

    Args:
        sql:    The SQL string generated by the LLM agent.
        org_id: The authenticated organization's ID.

    Returns:
        The stripped SQL string if all checks pass.

    Raises:
        SQLSecurityError: If any check fails. Callers must NOT execute the SQL.
    """
    sql = sql.strip()

    _check_not_empty(sql)
    _check_select_only(sql)
    _check_allowed_tables(sql)
    _check_org_id_present(sql, org_id)
    _check_no_injection(sql)

    logger.info(f"[SQL_SECURITY] Query passed all checks for org_id={org_id}: {sql[:80]}")
    return sql
